### ISSUE TITLE
path-specific ignore list?

### ISSUE THREAD

**Issue by lougreenwood** [ef4/prember-crawler#1]
Very useful plugin, thanks!

I'm currently using a simple, un-customised crawler (so crawling all links from `/`) however, this picks up links on my home page to my (external) OAuth server.

Ideally, I would like to configure the crawler to just ignore anything on the specific path `/oauth`.

The alternative is to tag all links from my home page with some social selector, but this doesn't seem to be scalable...

Thanks again!

**Comment by ef4** [comment]
We could add an `exclude` option that takes a regex or a function. It would test each URL. That would make a great PR that wouldn't be too hard if you want to have a go at it.

**Comment by ef4** [comment]
Closed in #2.
